package com.chisom.standardizationservice;

import lombok.AccessLevel;
import lombok.NoArgsConstructor;

@NoArgsConstructor(access = AccessLevel.PRIVATE)
public abstract class JwtUtils {

    public static final String INTERNAL_OPERATION_TOKEN = "Bearer eyJraWQiOiIxNjE2YmEzNGJhODAyZWY0NjBkODcyN2EzYTc3YmQ1NjY0NzAzNDZiMWEzYWYzNWQwZDgyYjg1NzIzNDJiZTQ1IiwiYWxnIjoiSFMyNTYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2xvZ2luLWRldi5jb20iLCJzdWIiOiI3NTBhZDE4OC00OGY5LTQyMzctODY0OC04NDg5YWEwZjllMTUiLCJhenAiOiI2ZWVmMTYyZi0yNGQ4LTQ3NGItODg5MS04MjY2NGUxNzIwYjQiLCJhdWQiOiJodHRwczovL3N0YW5kYXJkaXphdGlvbi1zZXJ2aWNlLmNvbSIsImp0aSI6Ijc1MTUwMThjLTFjMTMtNDFlYi1hM2FlLTU5MTExNmE1MTBlNSIsImd0eSI6ImNsaWVudF9jcmVkZW50aWFscyIsImlhdCI6MTc1NDgzODc3MSwibmJmIjoxNzU0ODM4NzcxLCJleHAiOjM2NDgyOTQ3NzEsInNjb3BlIjoiaW50ZXJuYWwtb3BlcmF0aW9uIn0.kYQZpx3UiJq6O4NY25Bg0PcBV2s7aMSjY204UllAc1Q";
}
